"""
Synthetic health data generator for Bios anomaly detection model.

Generates realistic 9-feature z-score vectors representing normal and
anomalous health states. Features are z-scores from personal baselines,
matching the input spec in TFLiteAnomalyModel.kt.

Feature layout:
  [0] heart_rate               (z-score from resting baseline)
  [1] heart_rate_variability   (z-score)
  [2] resting_heart_rate       (z-score)
  [3] blood_oxygen             (z-score)
  [4] respiratory_rate         (z-score)
  [5] skin_temperature_deviation (z-score)
  [6] sleep_duration           (z-score)
  [7] steps                    (z-score)
  [8] active_calories          (z-score)

Physiological priors:
  - Normal daily variation: most z-scores cluster within [-1.5, 1.5]
  - Metrics are correlated (e.g., low HRV often coincides with high resting HR)
  - Anomalous states show multi-signal deviation matching ConditionPatterns.kt
"""

import numpy as np


# Correlation structure for normal physiological state.
# Positive = tend to move together, negative = inverse relationship.
# Based on literature: Mishra 2020, Quer 2021, Plews 2013.
NORMAL_CORRELATION = np.array([
    # HR    HRV    rHR    SpO2   RR     temp   sleep  steps  cal
    [ 1.0, -0.5,   0.7,  -0.1,   0.3,   0.1,  -0.1,   0.4,  0.4],  # HR
    [-0.5,  1.0,  -0.6,   0.1,  -0.2,  -0.1,   0.2,  -0.1, -0.1],  # HRV
    [ 0.7, -0.6,   1.0,  -0.1,   0.2,   0.2,  -0.2,   0.1,  0.1],  # rHR
    [-0.1,  0.1,  -0.1,   1.0,  -0.1,  -0.1,   0.1,   0.0,  0.0],  # SpO2
    [ 0.3, -0.2,   0.2,  -0.1,   1.0,   0.2,  -0.1,   0.1,  0.1],  # RR
    [ 0.1, -0.1,   0.2,  -0.1,   0.2,   1.0,  -0.1,   0.0,  0.0],  # temp
    [-0.1,  0.2,  -0.2,   0.1,  -0.1,  -0.1,   1.0,   0.1,  0.1],  # sleep
    [ 0.4, -0.1,   0.1,   0.0,   0.1,   0.0,   0.1,   1.0,  0.8],  # steps
    [ 0.4, -0.1,   0.1,   0.0,   0.1,   0.0,   0.1,   0.8,  1.0],  # cal
])

FEATURE_NAMES = [
    "heart_rate", "heart_rate_variability", "resting_heart_rate",
    "blood_oxygen", "respiratory_rate", "skin_temperature_deviation",
    "sleep_duration", "steps", "active_calories",
]


def generate_normal(n: int, rng: np.random.Generator) -> np.ndarray:
    """Generate n samples of normal physiological z-score vectors.

    Normal state: z-scores drawn from N(0, 0.7) with physiological
    correlation structure. Most values fall within [-1.5, 1.5].
    """
    # Scale down variance so normal data clusters tightly around 0
    std_devs = np.full(9, 0.7)
    cov = np.outer(std_devs, std_devs) * NORMAL_CORRELATION
    samples = rng.multivariate_normal(np.zeros(9), cov, size=n)
    return samples.astype(np.float32)


def generate_anomalous(n: int, rng: np.random.Generator) -> np.ndarray:
    """Generate n samples of anomalous health states.

    Anomalies are generated by simulating known clinical patterns from
    ConditionPatterns.kt, each with physiologically plausible signal
    combinations.
    """
    patterns = [
        _infection_onset,
        _cardiovascular_stress,
        _overtraining,
        _sleep_disruption,
        _metabolic_drift,
        _respiratory_infection,
        _chronic_inflammation,
        _deconditioning,
    ]

    samples_per_pattern = n // len(patterns)
    remainder = n % len(patterns)

    all_samples = []
    for i, pattern_fn in enumerate(patterns):
        count = samples_per_pattern + (1 if i < remainder else 0)
        all_samples.append(pattern_fn(count, rng))

    result = np.concatenate(all_samples, axis=0)
    rng.shuffle(result)
    return result.astype(np.float32)


def _with_noise(base: np.ndarray, rng: np.random.Generator,
                noise_std: float = 0.3) -> np.ndarray:
    """Add per-sample noise to a base pattern."""
    return base + rng.normal(0, noise_std, size=base.shape)


def _infection_onset(n: int, rng: np.random.Generator) -> np.ndarray:
    """Elevated HR, rHR, temp; suppressed HRV, SpO2; disrupted sleep.
    Based on Mishra 2020, Quer 2021."""
    samples = generate_normal(n, rng)
    samples[:, 0] += rng.uniform(1.5, 3.5, n)    # HR up
    samples[:, 1] -= rng.uniform(1.5, 3.0, n)    # HRV down
    samples[:, 2] += rng.uniform(1.5, 3.0, n)    # rHR up
    samples[:, 3] -= rng.uniform(1.0, 2.5, n)    # SpO2 down
    samples[:, 4] += rng.uniform(1.0, 2.5, n)    # RR up
    samples[:, 5] += rng.uniform(1.5, 3.0, n)    # temp up
    samples[:, 6] -= rng.uniform(1.0, 2.0, n)    # sleep down
    return samples


def _cardiovascular_stress(n: int, rng: np.random.Generator) -> np.ndarray:
    """Elevated rHR, suppressed HRV, SpO2 dip. Plews 2013."""
    samples = generate_normal(n, rng)
    samples[:, 0] += rng.uniform(1.0, 2.5, n)    # HR up
    samples[:, 1] -= rng.uniform(2.0, 4.0, n)    # HRV sharply down
    samples[:, 2] += rng.uniform(2.0, 3.5, n)    # rHR up
    samples[:, 3] -= rng.uniform(0.5, 1.5, n)    # SpO2 slight dip
    return samples


def _overtraining(n: int, rng: np.random.Generator) -> np.ndarray:
    """High HR/rHR, suppressed HRV, disrupted sleep, elevated activity."""
    samples = generate_normal(n, rng)
    samples[:, 0] += rng.uniform(1.5, 3.0, n)    # HR up
    samples[:, 1] -= rng.uniform(1.5, 3.0, n)    # HRV down
    samples[:, 2] += rng.uniform(1.0, 2.5, n)    # rHR up
    samples[:, 6] -= rng.uniform(1.0, 2.0, n)    # sleep down
    samples[:, 7] += rng.uniform(2.0, 4.0, n)    # steps way up
    samples[:, 8] += rng.uniform(2.0, 4.0, n)    # calories way up
    return samples


def _sleep_disruption(n: int, rng: np.random.Generator) -> np.ndarray:
    """Primary sleep deficit with secondary HR/HRV effects. Prather 2015."""
    samples = generate_normal(n, rng)
    samples[:, 6] -= rng.uniform(2.0, 4.0, n)    # sleep sharply down
    samples[:, 1] -= rng.uniform(1.0, 2.0, n)    # HRV down
    samples[:, 2] += rng.uniform(0.5, 1.5, n)    # rHR slightly up
    samples[:, 7] -= rng.uniform(1.0, 2.0, n)    # steps down (fatigue)
    return samples


def _metabolic_drift(n: int, rng: np.random.Generator) -> np.ndarray:
    """Gradual metabolic changes: weight-related signals. Zeevi 2015."""
    samples = generate_normal(n, rng)
    samples[:, 2] += rng.uniform(1.0, 2.0, n)    # rHR up
    samples[:, 4] += rng.uniform(0.5, 1.5, n)    # RR slight up
    samples[:, 5] += rng.uniform(0.5, 1.5, n)    # temp slight up
    samples[:, 7] -= rng.uniform(1.5, 3.0, n)    # steps down
    samples[:, 8] -= rng.uniform(1.5, 3.0, n)    # calories down
    return samples


def _respiratory_infection(n: int, rng: np.random.Generator) -> np.ndarray:
    """Respiratory-dominant: SpO2 drop, RR up, temp up."""
    samples = generate_normal(n, rng)
    samples[:, 3] -= rng.uniform(2.0, 4.0, n)    # SpO2 sharply down
    samples[:, 4] += rng.uniform(2.0, 3.5, n)    # RR up
    samples[:, 5] += rng.uniform(1.5, 3.0, n)    # temp up
    samples[:, 1] -= rng.uniform(1.0, 2.0, n)    # HRV down
    samples[:, 6] -= rng.uniform(1.0, 2.5, n)    # sleep down
    return samples


def _chronic_inflammation(n: int, rng: np.random.Generator) -> np.ndarray:
    """Subtle persistent elevation across multiple signals. Furman 2019."""
    samples = generate_normal(n, rng)
    # Smaller but persistent deviations across many signals
    samples[:, 0] += rng.uniform(0.8, 1.8, n)    # HR slightly up
    samples[:, 1] -= rng.uniform(0.8, 1.8, n)    # HRV slightly down
    samples[:, 2] += rng.uniform(0.8, 1.5, n)    # rHR slightly up
    samples[:, 4] += rng.uniform(0.5, 1.2, n)    # RR slightly up
    samples[:, 5] += rng.uniform(0.8, 1.5, n)    # temp slightly up
    samples[:, 6] -= rng.uniform(0.5, 1.2, n)    # sleep slightly down
    return samples


def _deconditioning(n: int, rng: np.random.Generator) -> np.ndarray:
    """Cardiorespiratory deconditioning: rising rHR, falling activity.
    Booth 2012."""
    samples = generate_normal(n, rng)
    samples[:, 2] += rng.uniform(1.5, 3.0, n)    # rHR up
    samples[:, 1] -= rng.uniform(1.0, 2.5, n)    # HRV down
    samples[:, 7] -= rng.uniform(2.0, 4.0, n)    # steps way down
    samples[:, 8] -= rng.uniform(2.0, 4.0, n)    # calories way down
    return samples


def generate_dataset(
    n_normal: int = 15000,
    n_anomalous: int = 5000,
    seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Generate train/test split of normal and anomalous data.

    Returns (X_train_normal, X_test_normal, X_test_anomalous, X_all_test_labels).

    Training set is normal-only (autoencoder learns healthy patterns).
    Test set is mixed normal + anomalous with labels.
    """
    rng = np.random.default_rng(seed)

    normal = generate_normal(n_normal, rng)
    anomalous = generate_anomalous(n_anomalous, rng)

    # 80/20 split for normal data
    split = int(n_normal * 0.8)
    X_train = normal[:split]
    X_test_normal = normal[split:]

    # Test set: remaining normal + all anomalous
    X_test = np.concatenate([X_test_normal, anomalous], axis=0)
    y_test = np.concatenate([
        np.zeros(len(X_test_normal)),   # 0 = normal
        np.ones(len(anomalous)),        # 1 = anomalous
    ])

    # Shuffle test set
    idx = rng.permutation(len(X_test))
    X_test = X_test[idx]
    y_test = y_test[idx]

    return X_train, X_test, y_test


if __name__ == "__main__":
    X_train, X_test, y_test = generate_dataset()
    print(f"Training set (normal only): {X_train.shape}")
    print(f"Test set (mixed):           {X_test.shape}")
    print(f"Test labels:                {int(y_test.sum())} anomalous / {int((1-y_test).sum())} normal")
    print(f"\nTraining feature stats (should cluster around 0):")
    print(f"  Mean: {X_train.mean(axis=0).round(2)}")
    print(f"  Std:  {X_train.std(axis=0).round(2)}")
